version: "3.8"

services:
  server:
    build: .
    container_name: rewards-portal-server
    image: lugmanhk/rewards-portal-backend:0.0.1
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL="postgresql://admin:admin@postgres:5433/rewards"
      - CLIENT_ID=hzLBzEbDE3wuauGwXGPT7xMjat16WA02
      - CLIENT_SECRET=94TokbY4u0ouokddRLb3ECkceqKUzk03fuWFz15Jgeajq7s5KQb9PODT9OKAAFv4
      - REALM=rewards-portal
  postgres:
    container_name: "rp-postgres"
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rewards
    ports:
      - "5433:5433"
    volumes:
      - ./postgres:/var/lib/postgresql/data